#!/bin/bash
# This script was generated by setup.sh
# It provides a convenient way to run the demo with dashboard

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=========================================="
echo "Multi-Step LLM Article Processor - Generated Run Script"
echo "=========================================="
echo ""

# Check for virtual environment
if [ ! -d ".venv" ]; then
    echo "Error: Virtual environment not found."
    echo "Please run setup.sh first from the parent directory."
    exit 1
fi

# Activate virtual environment
source .venv/bin/activate

# Check for API key
if [ -z "$OPENAI_API_KEY" ]; then
    echo "Warning: OPENAI_API_KEY not set."
    echo "Please set it: export OPENAI_API_KEY='your-key-here'"
    exit 1
fi

# Start dashboard if not running
if ! pgrep -f "dashboard.py" > /dev/null; then
    echo "Starting dashboard..."
    python dashboard.py > dashboard.log 2>&1 &
    sleep 2
    echo "Dashboard available at: http://localhost:5000"
fi

# Run the main demo
echo ""
echo "Running article processing demo..."
echo "Check dashboard at http://localhost:5000 for live metrics"
echo ""

python main.py

echo ""
echo "Demo completed!"
echo "Dashboard is still running at http://localhost:5000"
echo "To stop dashboard: pkill -f dashboard.py"
echo ""

deactivate
